server:
  port: ${port:9000}  # 动态端口 ，从配置窗口中动态获取端口  ，默认是9000
#  从 edit configuration 的VM options   -Dport=9001   动态设置端口


spring:
  application:
    name: serve-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#logging:
#  level:
#    root: info
#    org.springframework: info