server:
  port: 8000


spring:
  application:
    name: serve-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        namespace: 2864cc57-a2de-44f8-8ff5-eff383af834d   # 对应 nacos 中的 命名空间 默认public
#        cluster-name: DEFAULT    #集群名

logging:
  level:
    root: info
    org.springframework: info